export const galleryPhotos = [
  {
    src: "/photos/arjen-sahil.jpg",
    span: "col-span-2 row-span-2",
    tr: "Abana Sahili",
    en: "Abana Beach",
  },
  {
    src: "/photos/arjen-gokkusagi.jpg",
    span: "",
    tr: "Yağmur sonrası gökkuşağı",
    en: "Rainbow after the rain",
  },
  {
    src: "/photos/arjen-yesilyuva.jpg",
    span: "",
    tr: "Yeşilyuva Tabiat Parkı",
    en: "Yeşilyuva Nature Park",
  },
  {
    src: "/photos/arjen-kordon.jpg",
    span: "",
    tr: "Kordon ve sahil",
    en: "Promenade and coast",
  },
  {
    src: "/photos/arjen-sahil-koy.jpg",
    span: "",
    tr: "Hacıveli koyu",
    en: "Hacıveli cove",
  },
  {
    src: "/photos/arjen-dalga.jpg",
    span: "",
    tr: "Kayalıklar ve dalga",
    en: "Cliffs and surf",
  },
  {
    src: "/photos/arjen-piknik.jpg",
    span: "col-span-2",
    tr: "Deniz manzaralı piknik",
    en: "Picnic with a sea view",
  },
  {
    src: "/photos/arjen-gunbatimi.jpg",
    span: "",
    tr: "Sahil yolunda gün batımı",
    en: "Sunset on the coastal road",
  },
  {
    src: "/photos/arjen-palmiye.jpg",
    span: "",
    tr: "Fırtınalı Karadeniz",
    en: "Stormy Black Sea",
  },
  {
    src: "/photos/arjen-kasaba.jpg",
    span: "",
    tr: "İlçe ve deniz",
    en: "Town and sea",
  },
  {
    src: "/photos/arjen-orman.jpg",
    span: "",
    tr: "Kent ormanı",
    en: "Forest trail",
  },
  {
    src: "/photos/arjen-mesire.jpg",
    span: "",
    tr: "Mesire alanı",
    en: "Picnic woods",
  },
  {
    src: "/photos/arjen-meydan.jpg",
    span: "",
    tr: "Abana meydanı",
    en: "Abana square",
  },
  {
    src: "/photos/arjen-konak.jpg",
    span: "",
    tr: "Tarihi ahşap konak",
    en: "Historic wooden mansion",
  },
  {
    src: "/photos/arjen-kopuk.jpg",
    span: "col-span-2",
    tr: "Dalga ve koyu kum",
    en: "Surf and dark sand",
  },
  {
    src: "/photos/arjen-falez.jpg",
    span: "",
    tr: "Falez ve turkuaz su",
    en: "Cliff and turquoise water",
  },
  {
    src: "/photos/arjen-kayalik.jpg",
    span: "",
    tr: "Kayalıklardan alacakaranlık",
    en: "Dusk from the rocks",
  },
  {
    src: "/photos/arjen-bayrak.jpg",
    span: "",
    tr: "Bayrak tepesi",
    en: "Flag hill",
  },
  {
    src: "/photos/arjen-yokus.jpg",
    span: "",
    tr: "Yeşil yamaç",
    en: "Green hillside",
  },
  {
    src: "/photos/arjen-gokkusagi-2.jpg",
    span: "",
    tr: "Gökkuşağı",
    en: "Rainbow",
  },
  {
    src: "/photos/arjen-dalga-2.jpg",
    span: "",
    tr: "Sahilde köpük",
    en: "Foam on the shore",
  },
  {
    src: "/photos/arjen-mendirek.jpg",
    span: "",
    tr: "Mendirek",
    en: "Breakwater",
  },
  {
    src: "/photos/arjen-tepe-kafe.jpg",
    span: "",
    tr: "Tepedeki cam kafe",
    en: "Hillside glass cafe",
  },
  {
    src: "/photos/arjen-piknik-2.jpg",
    span: "",
    tr: "Çamlıkta piknik",
    en: "Picnic among the pines",
  },
  {
    src: "/photos/arjen-piknik-3.jpg",
    span: "",
    tr: "Orman içi mesire",
    en: "Woodland picnic spot",
  },
  {
    src: "/photos/arjen-koy.jpg",
    span: "col-span-2",
    tr: "Koy manzarası",
    en: "Bay view",
  },
  {
    src: "/photos/arjen-alacakaranlik.jpg",
    span: "",
    tr: "Alacakaranlık",
    en: "Twilight",
  },
  {
    src: "/photos/arjen-kedi.jpg",
    span: "",
    tr: "Abana kedisi",
    en: "Abana cat",
  },
  {
    src: "/photos/arjen-kedi-2.jpg",
    span: "",
    tr: "Sokak kedisi",
    en: "Street cat",
  },
  {
    src: "/photos/arjen-kedi-gece.jpg",
    span: "",
    tr: "Gece kedisi",
    en: "Cat at night",
  },
] as const;
