/** Photos used on the site. Arjen originals live in photos-arjen; these are web-sized copies. */
export const photos = {
  sahil: "/photos/arjen-sahil.jpg",
  sahilKoy: "/photos/arjen-sahil-koy.jpg",
  kordon: "/photos/arjen-kordon.jpg",
  dalga: "/photos/arjen-dalga.jpg",
  kopuk: "/photos/arjen-kopuk.jpg",
  gokkusagi: "/photos/arjen-gokkusagi.jpg",
  yesilyuva: "/photos/arjen-yesilyuva.jpg",
  piknik: "/photos/arjen-piknik.jpg",
  orman: "/photos/arjen-orman.jpg",
  mesire: "/photos/arjen-mesire.jpg",
  meydan: "/photos/arjen-meydan.jpg",
  palmiye: "/photos/arjen-palmiye.jpg",
  kasaba: "/photos/arjen-kasaba.jpg",
  konak: "/photos/arjen-konak.jpg",
  gunbatimi: "/photos/arjen-gunbatimi.jpg",
  bayrak: "/photos/arjen-bayrak.jpg",
  kayalik: "/photos/arjen-kayalik.jpg",
  falez: "/photos/arjen-falez.jpg",
  yokus: "/photos/arjen-yokus.jpg",
  kanyon: "/photos/haciveli-kopru.jpg",
  toza: "/photos/toza-seyir.jpg",
  cami: "/photos/abana-cami.jpg",
} as const;
